version: '3.8'

services:
  app:
    container_name: kapunun
    build: .
    restart: always
    ports:
      - "1111:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      # Add other environment variables here if needed
      # - NEXT_PUBLIC_...
